version: "3.7"

services:
  app-voting-system:
    container_name: app-vs-lifters
    image: desafio/app-vs:0.0.1
    restart: always
    depends_on:
      - db-voting-system
      - cache-redis-voting-system
    ports:
      - "8080:8080"

  db-voting-system:
    container_name: db-vs-lifters
    image: bitnami/postgresql
    restart: always
    environment:
      POSTGRES_DB: db-vs-lifters
      POSTGRES_USER: lifters
      POSTGRES_PASSWORD: lifters
    ports:
      - "5432:5432"
    volumes:
      - db-vs-lifters:/var/lib/postgresql/data

  cache-redis-voting-system:
    container_name: cache-redis-vs-lifters
    image: redis
    ports:
      - "6379:6379"

volumes:
  db-vs-lifters:
